import Head from "next/head";
import Image from "next/image";
import Button from "../components/Button";
import Logos from "../components/Logos";
import Contact from "../components/Contact";
import { useRouter } from "next/router";
import Content from "../components/content";
import Navbar from "../components/Navbar";

export default function Home() {
  const router = useRouter();
  function service() {
    router.push("/Services");
  }
  function about() {
    router.push("/About");
  }
  return (
    <>
      <Head>
        <title>BuildIt</title>

        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      {/* home content */}
      <div className="bg-hero-pattern relative overflow-y-hidden z-10 ">
        <Navbar />
        <div className=" absolute top-0 right-0  bg-no-repeat ">
          <img src="bg1.svg " className="object-cover " alt="bg1" />
        </div>

        <div className=" flex md:px-32 space-x-5 justify-between mx-auto pb-20 container items-center relative">
          {/* page title */}
          <div className=" flex flex-col space-y-20">
            <div className="flex flex-col space-y-5">
              <h1 className="text-darkgenoa font-bold text-6xl">
                Development company
              </h1>
              <p className="text-genoa text-base">
                Forward-thinking real estate developer, owner <br /> and
                investor with a reputation
              </p>
            </div>
            {/* buttons */}
            <div className="text-xs font-bold flex space-x-3 ">
              <Button
                text="Service"
                style={"bg-genoa p-5 shadow-2xl text-white shadow-blue-600"}
                onclick={service}
              />

              <Button
                text="About The Company"
                style={" bg-lightindigo py-5 px-10  text-darkgenoa "}
                onclick={about}
              />
            </div>
          </div>
          {/* images */}
          <div className="flex flex-col gap-5 ">
            <div className="flex items-end gap-5">
              <div>
                <img src="/house3.svg" alt="house3" />
              </div>
              <div>
                <img src=" /house4.svg " alt="house4" />
              </div>
              <div>
                <img src="/house1.svg"   alt="house1" />
              </div>
            </div>
            <div className="flex items-start gap-5">
              <div>
                <img src="/house2svg.svg"  alt="house2"  />
              </div>
              <div>
                <img src="/house5.svg"  alt="house5"  />
              </div>
            </div>
          </div>
        </div>
      </div>
      {/* innovative execurion */}
      <div className="flex flex-col space-y-20 justify-center items-center mx-auto container pt-32  pb-32  md:px-32  ">
        <div>
          <p className="text-genoa text-3xl font-bold">Innovative Execution</p>
        </div>
        {/* cards */}
        <div className="grid grid-cols-3 gap-10">
          {/* card 1 */}
          <div className="flex flex-col space-y-5">
            <div className="p-4 rounded-md bg-darkgenoa shadow-md  max-w-fit">
              <img src="/serviceicon1.svg"  alt="icon"/>
            </div>
            <h1 className="text-2xl text-darkgenoa font-bold">
              Featured Listing
            </h1>
            <p className="text-genoa text-base">
              Lorem ipsum dolor sit amet, consectetur adipiscing elit.{" "}
            </p>
          </div>
          {/* card 2 */}
          <div className="flex flex-col space-y-5">
            <div className="p-4 rounded-md bg-darkgenoa shadow-md  max-w-fit">
              <img src="/serviceicon2.svg" alt="icon" />
            </div>
            <h1 className="text-2xl text-darkgenoa font-bold">
              Featured Listing
            </h1>
            <p className="text-genoa text-base">
              Lorem ipsum dolor sit amet, consectetur adipiscing elit.{" "}
            </p>
          </div>
          {/* card 3 */}
          <div className="flex flex-col space-y-5">
            <div className="p-4 rounded-md bg-darkgenoa shadow-md  max-w-fit">
              <img src="/serviceicon3.svg" alt="icon"/>
            </div>
            <h1 className="text-2xl text-darkgenoa font-bold">
              Featured Listing
            </h1>
            <p className="text-genoa text-base">
              Lorem ipsum dolor sit amet, consectetur adipiscing elit.{" "}
            </p>
          </div>
        </div>
      </div>

      {/* Patners */}
      <div className="bg-innovative-bg py-20 ">
        <Logos />
        <div className="flex gap-10 mx-auto md:px-32 container  items-center   ">
          <div className="w-full">
            <img src="/partner.svg" alt="partner"/>
          </div>
          <div className="flex flex-col space-y-16 w-full">
            <Content
              title={"About us"}
              subtitle={"Owner and investor with a reputation"}
              paragraph={
                "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nunc elit sem, vestibulum sed leo eu, malesuada pharetra mauris. Integer rhoncus, eros vel euismod tempor, ipsum magna tristique nisi, quis ullamcorper enim magna eu orci. Sed semper ex quis semper aliquet. Cras hendrerit molestie sapien sed fermentum. Mauris dui tortor, viverra vel ultrices in, congue sed ex."
              }
              styles={"space-y-5"}
            />
            <div>
              <Button
                text="Explore "
                style={"py-4 bg-genoa px-6 text-white w-1/2"}
              />
            </div>
          </div>
        </div>
      </div>

      <div className="grid grid-cols-2 mx-auto container md:px-32 py-20 my-32 items-center gap-5 ">
        <div className="flex flex-col space-y-5">
          <Content
            title={"Available properties"}
            subtitle={"Featuring Listing"}
            paragraph={
              "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nunc elit sem, vestibulum sed leo eu, malesuada pharetra mauris. Integer rhoncus, eros vel euismod tempor, ipsum magna tristique nisi, quis ullamcorper enim magna eu orci. Sed semper ex quis semper aliquet. Cras hendrerit molestie sapien sed fermentum. Mauris dui tortor, viverra vel ultrices in, congue sed ex."
            }
            styles={"space-y-5"}
          />
          <div className="">
            <Button
              text="Explore "
              style={"py-4 bg-genoa px-6 text-white w-1/2"}
            />
          </div>
        </div>
        {/* images */}
        <div className="flex gap-3">
          <div className="flex flex-col gap-3 ">
            <div>
              <img src="/projectimg1.svg" alt="project"/>
            </div>
            <div>
              <img src="/projectimg2.svg" alt="project" />
            </div>
          </div>
          <div className="flex flex-col gap-3">
            <div>
              <img src="/projectimg3.svg" alt="project" />
            </div>
            <div>
              <img src="/projectimg4.svg" alt="project" />
            </div>
          </div>
        </div>
      </div>
      <div className="bg-innovative-bg">
      <div className="flex flex-col mx-auto md:px-32 container py-52 space-y-10 ">
        <div className="flex flex-col justify-center items-center">
          <h3 className="text-genoa text-base font-medium">Socials</h3>
          <h1 className="text-4xl font-bold text-darkgenoa">On Instagram</h1>
        </div>
        <div className="grid grid-cols-3 gap-3  ">
          <div>
            <img src="/card1.svg" alt="card"/>
          </div>
          <div>
            <img src="/card2.svg" alt="card"/>
          </div>
          <div>
            <img src="/card3.svg" alt="card"/>
          </div>
          <div>
            <img src="/card4.svg"  alt="card"/>
          </div>
          <div>
            <img src="/card5.svg" alt="card" />
          </div>
          <div>
            <img src="/card6.svg" alt="card"/>
          </div>
        </div>
      </div>
      </div>
      <Contact />
    </>
  );
}
