import Head from 'next/head'
import Image from 'next/image'
import Button from '../../components/button'
import Logos from '../../components/logos'
import Contact from '../../components/Contact'


export default function Home() {
  return (
 <>
      <Head>
        <title>BuildIt</title>
        
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      {/* home content */}
    
      <div className=' flex md:px-32 space-x-5 justify-between mx-auto pb-64 container items-center'>
        
        {/* page title */}
        <div className=' flex flex-col space-y-20'>
          <div className='flex flex-col space-y-5'>
          <h1 className='text-darkgenoa font-bold text-6xl'>Development company</h1>
          <p className='text-genoa text-base'>Forward-thinking real estate developer, owner <br/> and investor with a reputation</p>
          </div>
          {/* buttons */}
          <div className='text-xs font-bold flex space-x-3 '>
            
            <Button text='Service' style={'bg-genoa p-5 shadow-2xl text-white shadow-blue-600'}/>
          
            <Button text='About The Company' style={' bg-lightindigo py-5 px-10  text-darkgenoa '}/>
          </div>
        </div>
        {/* images */}
        <div className='flex flex-col gap-5 '>
          <div className='flex items-end gap-5'>
            <div>

            <img src='/house3.svg' />
            </div>
            <div>

            <img src=' /house4.svg '/>
            </div>
            <div>

            <img src='/house1.svg' />
            </div>
            
          </div>
          <div className='flex items-start gap-5'>
            <div>

          <img src='/house2svg.svg' />
            </div>
            <div>

            <img src='/house5.svg' />
            </div>
           
          </div>

        </div>

      </div>
      {/* innovative execurion */}
      <div className='flex flex-col space-y-20 justify-center items-center mx-auto container mt-20 mb-52 pt-32  pb-72  md:px-32'>
        <div>
          <p className='text-genoa text-3xl font-bold'>Innovative Execution</p>
        </div>
        {/* cards */}
        <div className='grid grid-cols-3 gap-10'>
          {/* card 1 */}
          <div className='flex flex-col space-y-5'>
            <div className='p-4 rounded-md bg-darkgenoa shadow-md  max-w-fit'><img src='/serviceicon1.svg' /></div>
            <h1 className='text-2xl text-darkgenoa font-bold'>Featured Listing</h1>
            <p className='text-genoa text-base'>Lorem ipsum dolor sit amet, consectetur adipiscing elit. </p>
          </div>
            {/* card 2 */}
            <div className='flex flex-col space-y-5'>
            <div className='p-4 rounded-md bg-darkgenoa shadow-md  max-w-fit'><img src='/serviceicon2.svg' /></div>
            <h1 className='text-2xl text-darkgenoa font-bold'>Featured Listing</h1>
            <p className='text-genoa text-base'>Lorem ipsum dolor sit amet, consectetur adipiscing elit. </p>
          </div>
            {/* card 3 */}
            <div className='flex flex-col space-y-5'>
            <div className='p-4 rounded-md bg-darkgenoa shadow-md  max-w-fit'><img src='/serviceicon3.svg' /></div>
            <h1 className='text-2xl text-darkgenoa font-bold'>Featured Listing</h1>
            <p className='text-genoa text-base'>Lorem ipsum dolor sit amet, consectetur adipiscing elit. </p>
          </div>



        </div>

      </div>
      <Logos/>
      {/* Patners */}
      <div className='flex gap-10 mx-auto md:px-32 container  items-center py-10 mb-20 '>
        <div className='w-full'><img src='/partner.svg'/></div>
        <div className='flex flex-col space-y-16 w-full'>
          <h3 className='text-genoa text-base font-medium'>About us</h3>
          <h1 className='text-4xl font-bold text-darkgenoa'>Owner and investor with a reputation</h1>
          <p className=' text-base text-genoa leading-8'>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nunc elit sem, vestibulum sed leo eu, malesuada pharetra mauris. Integer rhoncus, eros vel euismod tempor, ipsum magna tristique nisi, quis ullamcorper enim magna eu orci. Sed semper ex quis semper aliquet. Cras hendrerit molestie sapien sed fermentum. Mauris dui tortor, viverra vel ultrices in, congue sed ex.</p>
          <div>
          <Button text='Explore ' style={'py-4 bg-genoa px-6 text-white w-1/2'} />
          </div>
        </div>
        

      </div>
      <div className='grid grid-cols-2 mx-auto container md:px-32 py-20 my-32 items-center gap-5'>
        <div className='flex flex-col space-y-5'>
          <h3 className='text-genoa text-base font-medium'>Available properties</h3>
          <h1 className='text-4xl font-bold text-darkgenoa'>Featuring Listing</h1>
          <p  className=' text-base text-genoa leading-8'>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nunc elit sem, vestibulum sed leo eu, malesuada pharetra mauris. Integer rhoncus, eros vel euismod tempor, ipsum magna tristique nisi, quis ullamcorper enim magna eu orci. Sed semper ex quis semper aliquet. Cras hendrerit molestie sapien sed fermentum. Mauris dui tortor, viverra vel ultrices in, congue sed ex.</p>
          <div>
          <Button text='Explore ' style={'py-4 bg-genoa px-6 text-white w-1/2'} />
          </div>
        </div>
        {/* images */}
        <div className='flex gap-3'>
          <div  className='flex flex-col gap-3 '>
            <div><img src='/projectimg1.svg'/></div>
            <div><img src='/projectimg2.svg'/></div>
          </div>
          <div  className='flex flex-col gap-3'>
            <div><img src='/projectimg3.svg'/></div>
            <div><img src='/projectimg4.svg'/></div>
          </div>

        </div>
      </div>
      <div className='flex flex-col mx-auto md:px-32 container my-32 py-52 space-y-10'>
        <div className='flex flex-col justify-center items-center'>
          <h3 className='text-genoa text-base font-medium'>Socials</h3>
          <h1 className='text-4xl font-bold text-darkgenoa'>On Instagram</h1>
        </div>
        <div className='grid grid-cols-3 gap-3  '>
          <div><img src='/card1.svg'/></div>
          <div><img src='/card2.svg'/></div>
          <div><img src='/card3.svg'/></div>
          <div><img src='/card4.svg'/></div>
          <div><img src='/card5.svg'/></div>
          <div><img src='/card6.svg'/></div>
        </div>
       
        
      </div>
      <Contact/>
     
  </>
    

  )
}
